version : '3'
services :
  php:
    image: cube43/docker-apache2-php:8.1
    volumes:
      - .:/var/www
    links:
       - web
  web:
    image: cube43/docker-nginx:release-1.0
    restart: always
    ports:
      - "8099:85"
    volumes:
      - .:/var/www
      - ./site.conf:/etc/nginx/conf.d/site.conf